# Generated by Django 4.2.7 on 2024-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='img',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото категории'),
        ),
    ]
