# Generated by Django 4.2.9 on 2024-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_categories_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='img',
            field=models.ImageField(blank=True, upload_to='cat', verbose_name='Фото категории'),
        ),
    ]
