# Generated by Django 4.2.5 on 2024-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_categories_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
