# Generated by Django 4.2.5 on 2024-03-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_posttasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttasks',
            options={'ordering': ['title'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачі'},
        ),
        migrations.AddField(
            model_name='posttasks',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
