# Generated by Django 4.2.5 on 2024-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_posttasks_options_posttasks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttasks',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
