# Generated by Django 4.2.5 on 2024-03-29 16:37

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttasks',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
    ]
